[workspace]
members = [
    "contracts/shared",
    "contracts/vault_router",
    "contracts/vault_flex",
    "contracts/vault_l3",
    "contracts/vault_l6",
    "contracts/vault_l12",
    "contracts/strategy_vault",
    "contracts/harvester",
    "contracts/governance"
]

[profile.release]
opt-level = "z"
overflow-checks = true
lto = true

[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "21.0.0"